apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::952244316771:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::952244316771:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5A3J2I90VBH9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-29T03:42:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2424"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 760b74e8-8038-4e6b-bcf8-19007ace86b3
